### PR TITLE
Feat/mpc 39/fix json type encoder to ignore invalid utf8 chars

### PR DESCRIPTION
**Pull request by komando82**
Add flag to ignore invalid utf8 on JsonTypeEncoder

### CODE REVIEW

**Comment by dominikzogg** [comment]
@healerz should we change that behavior by default?

**Comment by healerz** [comment]
@dominikzogg to me it would make sense to change the default behaviour, but wasn't sure if you'd agree :) We will change it (@komando82)

**Comment by dominikzogg** [comment]
@komando82 @healerz to me this is a bug fix, not a feature, i would not change the construct, add property, cause invalid signs in json means invalid json.

**Comment by dominikzogg** [comment]
@komando82 looks good, thank you

**Comment by dominikzogg** [comment]
https://github.com/chubbyphp/chubbyphp-serialization/releases/tag/2.14.1

**Pull request merged**
