### PR TITLE
Chore: add custom method to create exception and fix BC in isCompliant

### PR DESCRIPTION
**Pull request by marko-ilic**

### CODE REVIEW

**Review by healerz — APPROVED** [review]

**Comment by dominikzogg** [comment]
same applies to all object hints you did in the last PR (normalizer, field normalizer)

**Comment by healerz** [comment]
> same applies to all object hints you did in the last PR (normalizer, field normalize

@dominikzogg 
yes you're right :( shall we add a commented version of the methods (including the typehint) to the interfaces and deprecate the existing one?

**Comment by dominikzogg** [comment]
i will add those hints at 3.0, comments are needed as they where before

**Comment by dominikzogg** [comment]
thx

**Comment by dominikzogg** [comment]
@healerz its evil, but i think delete 2.13.0 would be a good idea in this case

**Comment by healerz** [comment]
> @healerz its evil, but i think delete 2.13.0 would be a good idea in this case

@dominikzogg hrhr, sometimes this causes issues for composer as far as I remember. But ok, to me it's ok either way, I would have done a 2.13.1

**Comment by dominikzogg** [comment]
i will add 2.13.1, but 2.13.0 should no be installed, and yes it breaks the composer.lock and caches.

**Comment by healerz** [comment]
@marko-ilic @dominikzogg 
I think we need to add back the test we deleted (now that we removed the type-hint again) which made sure that an exception is thrown if no object gets passed. I also think the piece of code which checked it is missing now.

**Comment by dominikzogg** [comment]
yea, but cause the internal typehint i can live with the status quo, thats the reason why i didn't wrote it before

**Pull request merged**
